### ISSUE TITLE
Experiencing frequent memory crashes that makes the plugin unusable

### ISSUE THREAD

**Issue by awordley** [alowaniak/music-replacer#23]
Firstly, I was excited to find that this plugin has been made available again after it was down for a while due to the 'Random' music button update, so thank you Alowaniak for restoring this amazing plugin.

However, I have ran into a couple of game-crashing issues that makes the plugin pretty much unusable. I use the plugin with a big directory of MP3's that I bulk override from my desktop, if that helps. Here's a few crashes I've noticed so far:

While listening to an overriden track, switching the music player to Manual mode and changing location causes Runelite to crash most the time, as if the game is trying to load the next area's music although in Manual Mode- which is conflicting with the plugin's override. It's something that's happened to me a fair bit although I'm not entirely sure why.

The game also seems to crash a lot inexplainably, such as just running around with the music player set to 'Area' mode, and more often than not when I'm Alt-Tabbing back on to the client after engaging with another window like a browser. These seem to be due to memory issues, as I've noticed crashes happen more frequently when I'm using Discord or playing a Youtube video in the background.

_Here is a copy of the log following a crash when changing areas with the plugin on._ 

2023-10-05 01:50:06 BST [Map loader] ERROR client-patch - Client error: map loading
java.lang.OutOfMemoryError: Java heap space
	at jt.<init>(jt.java:57994)
	at rl2.cs(rl2.java:60863)
	at rl2.run(rl2.java:57557)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-10-05 01:50:06 BST [Map loader] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
	at jt.<init>(jt.java:57994)
	at rl2.cs(rl2.java:60863)
	at rl2.run(rl2.java:57557)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-10-05 01:50:06 BST [Client] ERROR client-patch - Client error
java.lang.NullPointerException: null
	at client.hw(client.java:23063)
	at client.kq(client.java:6449)
	at client.hw(client.java:3098)
	at client.bo(client.java:1124)
	at bb.gv(bb.java:358)
	at bb.run(bb.java:335)
	at java.base/java.lang.Thread.run(Unknown Source)

_Here is a copy of the log following a crash when alt-tabbing back into runelite (Discord was open)._ 

023-10-05 14:47:07 BST [Client] ERROR client-patch - Client error
java.lang.OutOfMemoryError: Java heap space
	at ba.<init>(ba.java:25)
	at bb.au(bb.java:166)
	at bb.be(bb.java:396)
	at bb.qs(bb.java:387)
	at bb.run(bb.java:337)
	at java.base/java.lang.Thread.run(Unknown Source)

Not sure if this is helpful at all, I had no issues with the plugin previously and used it for almost a year before it first started breaking this summer. If it helps I play from the UK and have 16GB of ram on my Windows PC. I might be having problems with the JAco MP3 Player connecting with my PC, but honestly I have no idea how this plugin works at all - I'm just spitballing theories! Maybe converting all my tracks to .wav may fix this? 

If you could get back with any info/solutions that would be grately appreciated, this is by far my most loved and used plugin in Runelite!

**Comment by DanMossa** [comment]
@awordley Where did you locate the file with these errors?

My Runelite also crashes with this plugin enabled but I don't see any OutOfMemory errors.
