### ISSUE TITLE
Songs won't override 

### ISSUE THREAD

**Issue by TheSpicyJesus** [alowaniak/music-replacer#5]
2022-09-01 00:06:28 [pool-6-thread-1] WARN  n.a.runelite.musicreplacer.Tracks - Something went wrong when downloading for TrackOverride(name=Adventure, originalPath=NaLu2KzMDNs, fromLocal=false, additionalInfo={Name=Runescape 07 - Adventure (Trap Remix), Duration=PT2M21S, Uploader=OSRSBeatz})
java.io.IOException: Server returned HTTP response code: 502 for URL: https://alowan.nl/runelite-music-replacer/download/NaLu2KzMDNs?ext=.mp3
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	at nl.alowaniak.runelite.musicreplacer.Tracks.transferLink(Tracks.java:265)
	at nl.alowaniak.runelite.musicreplacer.Tracks.transfer(Tracks.java:228)
	at nl.alowaniak.runelite.musicreplacer.Tracks.createOverride(Tracks.java:159)
	at nl.alowaniak.runelite.musicreplacer.Tracks.lambda$createOverride$9(Tracks.java:146)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)  

Getting this error in the logs for every song when i try to run override I've tried reinstalling runelite and the plugin multiple times and clearing runelite cache. Wondering how to fix this issue appreciate you looking into this if you do thank you.

**Comment by alowaniak** [comment]
Apparently my server went down, should be fixed now.
