### ISSUE TITLE
Failed to override all songs

### ISSUE THREAD

**Issue by Jacob-Lasky** [alowaniak/music-replacer#7]
[client.log](https://github.com/alowaniak/music-replacer/files/9541818/client.log)

Every song is getting a 502 error from the URL.
```
2022-09-11 01:13:48 [pool-9-thread-1] WARN  n.a.runelite.musicreplacer.Tracks - Something went wrong when downloading for TrackOverride(name=Yesteryear, originalPath=WFXq4fLG4pc, fromLocal=false, additionalInfo={Name=Runescape 07 - Yesteryear (Trap Remix), Duration=PT4M1S, Uploader=OSRSBeatz})
java.io.IOException: Server returned HTTP response code: 502 for URL: https://alowan.nl/runelite-music-replacer/download/WFXq4fLG4pc?ext=.mp3
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	at nl.alowaniak.runelite.musicreplacer.Tracks.transferLink(Tracks.java:265)
	at nl.alowaniak.runelite.musicreplacer.Tracks.transfer(Tracks.java:228)
	at nl.alowaniak.runelite.musicreplacer.Tracks.createOverride(Tracks.java:159)
	at nl.alowaniak.runelite.musicreplacer.Tracks.lambda$createOverride$9(Tracks.java:146)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by alowaniak** [comment]
Does this happen for you always or just sometimes?
Might be a "hiccup" or some temporary issues with my server.
